# Generated by Django 5.1.1 on 2024-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fd_backend', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=16)),
                ('image_vec', models.JSONField(default=list, null=True)),
            ],
        ),
    ]
